### PR TITLE
Create wso2.md

### PR DESCRIPTION
**Pull request by imShakil**

### CODE REVIEW

**Comment by ossdhaval** [comment]
@imShakil Good detailed document. :+1:

**Comment by ossdhaval** [comment]
One question: This document uses Gluu 4.5, should we be targeting Gluu Flex in new documents?

And suggestions:
At the start of the document
- Add a short description about what is the usecase that we are targeting with this setup.
- An interaction diagram depicting a typical request flow among components would be great for visualizing the complete setup.

**Comment by imShakil** [comment]
> One question: This document uses Gluu 4.5, should we be targeting Gluu Flex in new documents?
> 
> And suggestions: At the start of the document
> 
> * Add a short description about what is the usecase that we are targeting with this setup.
> * An interaction diagram depicting a typical request flow among components would be great for visualizing the complete setup.

Thanks @ossdhaval 

I understand there is some information missing. I think I should place the `sequence diagram` at the beginning.

**Comment by imShakil** [comment]
I did not test yet with gluu flex, But I believe it will work with flex too.

**Pull request merged**
